### ISSUE TITLE
meeting 04.10.

### ISSUE THREAD

**Issue by martin-raden** [PerfectionMaschine/RNA-Playground#1]
- [x] + recursions mit visualisieren
- [x] + beschreibung der algorithmen (what-why-how); DOI-link zu originalartikeln
- [x] + split CSS in "header/footer" daten und "algo" daten
- [x] + traceback nach `k+1` gefundenen lösungen abbrechen; wenn `>k` lösungen gefunden: hinweis fuer nutzer, dass output liste unvollständig (ersetzt aktuellen Hint)
- [x] + table name links oben in tabelle jeweils (passend zur angezeigten rekursion)
- [x] + (wenn rest fertig ist) WSB mit den drei scoring functions (radiobutton mit text+formel) aus den folien und alpha/beta (integer [-10,10]) scoring parameter (!! rechne mit floats und runde auf 1 stelle nach dem komma im output !!; ggf. tracebackmatrix)

- [x] * sequenzen `S_1` und `S_2` nennen und andere parameter mit latexnamen ergänzen
- [x] * rechte zellenrand von "score" zelle fehlt
- [x] * Gotoh: lange beispiele verlassen unteren seitenrand
- [x] * matrizenvisualisierung ggf. in scrollable div: check ob korrekt gerendert, wenn nicht dann nicht
- [x] * alignmentliste auch ggf. in scrollable div
- [x] * code aus `function backtrace()` in die einzelnen algorithm js-files verteilen
- [x] * funktionsdokumentation (header); ggf fuer überschriebene funktionen einfach auf entsprechendes interface/superclass verweisen
- [x] * quellcode docu ergänzen

- [x] - alphabet beschränkung auf Buchstaben ohne Umlaute [a-zA-Z]* : automatisch Grossbuchstaben umwandeln
- [x] - min/max-abhängige automatische schranken für scoring parameter weglassen

**Comment by AlexanderMattheis** [comment]
**Bericht**
Also, die Aufgaben habe ich alle bearbeitet.
"matrizenvisualisierung ggf. in scrollable div: check ob korrekt gerendert, wenn nicht dann nicht"
war leider nicht so einfach zu machen.  Habe es über eine Stunde lang probiert hinzubekommen.
Ich denke, dass das Ganze machbar ist, aber da bräuchte ich deutlich mehr Zeit. 
Müsste mich da iwo einlesen und so.

"sequenzen S_1 und S_2 nennen und andere parameter mit latexnamen ergänzen"
Ich habe die Sequenzen a und b genannt, wie du zuerst vorgeschlagen hattest.
Das Problem, wenn man die Sequenzen S_1 und S_2 nennt:
in den Formeln hat man dann Doppelindizes, was verwirrend sein kann 
-> d(a,b) =... a_i == b_i
oder 
-> d(S_1,S_2) =... (S_1)_i == (S_2)_i

Ich könnte es, aber auch schnell in den Formeln in S_1, S_2 umbennen,
da die Konstanten alle in der defaults.js gespeichert sind.

"rechte zellenrand von "score" zelle fehlt"
Das war wohl ein Firefox-Bug. 
In der Developer-Version (also, vermutlich auch in der nächsten Firefox-Version) tritt er nicht auf
und auch in keinem anderen Browser. 
Habe jetzt die Tabellen umgeschrieben und den Footer
von der eigentlichen Tabelle separiert. Jetzt tritt das Problem nimmer auf.

Am Besten besprechen wir den Rest morgen,
heute säubere ich noch etwas den Code und so...

**Comment by martin-raden** [comment]
Moin, bzgl. sequenzbenennung: nimmer superscript, d.h. "S^1", dann passt das auch wieder mit den positionsindizes ala "S^{1}_i"

bis morgen,
der Martin

**Comment by martin-raden** [comment]
habs gerade nochmal angeschaut, vergiss, behalte sequenznamen "a" und "b", passt schon!

**Comment by martin-mann** [comment]
wichtiger punkt: bei SW kannst du die "similarity maximization" mal direkt aus dem interface nehmen, weil das nicht funktioniert! der "0" case zum abschneiden wird nie verwendet...

**Comment by AlexanderMattheis** [comment]
"matrizenvisualisierung ggf. in scrollable div: check ob korrekt gerendert, wenn nicht dann nicht"
funktioniert jetzt!!! :)
Habe jetzt einen anderen Ansatz probiert und voilà es funktioniert.
Weil, aber ich alle Eingaben über den InputProcessor an die Klassen schicke, 
hat das implementieren jetzt nochmal 90 Minuten gedauert. Aber es sieht gut aus.

**Comment by martin-raden** [comment]
*thumbsup*
