### ISSUE TITLE
input layouting via div enclosure

### ISSUE THREAD

**Issue by martin-raden** [PerfectionMaschine/RNA-Playground#11]
Moin,
beim integrieren ist mir dein css hacking aufgefallen, mit dem du die input fields positionierst. 👎 

bin dafuer, dass wir das system aus dem webserver übernehmen, da die entsprechenden [webserver css](http://rna.informatik.uni-freiburg.de/resources/corporate-design.css)-sachen eh eingebunden (werden sollten). sprich: es gibt ein div pro input zeile und darin divs mit festen breiten, um den content spaltenartig zu arrangieren.

```html
<div class="row">
   <div class="colW200"> ... label ... </div>
   <div class="colW600"> ... input field, recursion placeholder, ... </div>
</div>
```

bitte die html-files entsprechend umarbeiten.
Danke

**Comment by AlexanderMattheis** [comment]
[Erledigt] Hoffentlich passt das nun so...

**Comment by martin-raden** [comment]
hab mal in zwei html-files testweise reingeschaut, sieht gut aus! :) Danke!
