### ISSUE TITLE
meeting 08.11.2017

### ISSUE THREAD

**Issue by AlexanderMattheis** [PerfectionMaschine/RNA-Playground#14]
T-Coffee
- [x] global alignment parameter 
- [x] max anzahl opt alignments to use (getrennt glob/loc)
- [x] local stuff (am schluss)
- [x] bsp aus t-coffee paper als default
- [x] primary library anzeigen (irgendwie schön codiert, ggf. in scrollable div)
- [x] extended lib anzeigen
- [x] FD mit ext. lib (ggf. kompletten FD output einbetten)
- [x] SoP vom finalen alignment (müssen wir noch überlegen wie auszurechen/welche parameter)

**Comment by AlexanderMattheis** [comment]
Musste heute abend feststellen, dass ich T-Coffee doch nicht gelesen hatte,
sondern nur die Folien mal etwas genauer angeschaut hatte. 
Also, muss ich doch noch das Paper mir durchlesen.
Bin bis zur Signal Addition heute mit dem Programmieren mit Hilfe der Folien gekommen 
und bei dem Extension Step, 
muss ich nun ins Paper schauen, weil der noch nicht ganz klar ist von den Folien aus Bioinfo 2 her 
bzw mir ist nicht klar, ob die Formel EL... = L + sum.. das macht, was ich glaube. 
Glaube schon, dass ich vielleicht weiß, was der Schriit macht, aber will mich im Paper besser vergewissern... (muss ja auch noch dokumentieren^^)

**Comment by AlexanderMattheis** [comment]
Hi Martin,
Also ich habe nochmal nachgelesen (war etwas irritiert* und dachte ich hätte es falsch gemacht)
Im Original-Algorithmus wird nur ein Alignment verwendet pro Sequenz-Paar verwendet
wie bei Feng-Doolittle: (damit es möglichst schnell ist wie bei Feng-Doolittle)
Seite 206: Generating a primary library of alignments
Es werden nur (N*(N-1))/2 Paare angeschaut jeweils für das Globale und Lokale Alignment
(siehe Mail)

\* Als du gesagt hattest letzte Woche, dass ich "max anzahl opt alignments to use (getrennt glob/loc)"
implementieren soll, habe ich an die Gesamtzahl Alignments gedacht (nicht die pro Sequenz-Paar).
Also, dass ich z.B. mit max=2 Alignments (bei drei Sequenzen)
1. für Sequenzen a und Sequenz b ein Alignment erzeuge (Score 5)
2. für Sequenzen a und Sequenz c ein Alignment erzeuge (Score 4)
3. für Sequenzen b und Sequenz c ein Alignment erzeuge (Score 2)
und mir dann die besten 2 Alignments (mit den höchsten Scores) hole (hier ab und ac).
Genau das wird mit k=10 Alignments (also, man verbessert nicht alle globalen Alignments) für die Local Sachen nämlich gemacht 
und ich dachte du redest davon und wollte das implementieren. Soll, ich nun das implementieren was im Original geschrieben steht oder die Bias-Reduktion, die im Original-Algorithmus nicht enthalten ist (oder beides...)?
(eventuell ist das Zweite zeitaufwendig, weil ich nicht mehr direkt die Feng-Doolittle Sachen verwenden kann, da der sich nur ein Alignment berechnet)
Also, Bias wird anscheinend nur mit Hilfe der Lokalen Library reduziert, indem man die bestimmte
Stellen stärker gewichtet.

**Comment by martin-raden** [comment]
moin,
also die idee ist maximal *k* alignments *pro sequenzpaar* zu berechnen, um damit die diversität der alignmentdatenbank zu erhöhen. dass im paper nur eins verwendet wird, ist diversen dingen geschuldet, aber der clue am t-coffee ist, dass es beliebig viele integrieren kann und dann auch besser wird.

klärts das?

**Comment by martin-raden** [comment]
wenn ich *k=1* setze, bekomme ich damit wieder den im paper beschriebenen ansatz.. oder?

**Comment by martin-raden** [comment]
ok **primary library**
folie 14 hat nen fehler: das schwarze match^{1,2}_{2,2} zeigt im alignment auf die falsche spalte (schwarzer kringel für seq-2 sollte da sein, wo auch der rote ist (spalte 3))

![matchij-def](https://user-images.githubusercontent.com/22291305/33027529-9f012876-ce13-11e7-8b2a-5e476cbdca1d.png)

hab ich mal fürs nächste jahr geändert..

**Comment by martin-raden** [comment]
bzgl dem folgenden aus #16

<i>Also, ich glaube, dass es keine Stellen mit 0 geben kann im Original-Algorithmus,
denn die sind erst gar nicht definiert. Im Paper heißt es, dass nur für alignierte Stellen ein Gewicht existiert
und alle alignierten Stellen die Sequenz-Identität als Gewicht erhalten.
Ja, in den Vorlesungs-Folien ist es anders, aber im Paper steht von dem was auf den Folien bei der Extension zu sehen ist glaube ich nichts. Vorallem werden zweimal dieselben miteinander aligniert.</i>

steht im paper

<i>If we now look at the alignment of sequence A and sequence B through sequence C (Figure 2(c)), we can see that the A(G) and C(G) are aligned, as well as C(G) and A(G). We conclude that there is an alignment of A(G) with B(G) through sequence C. We associate that alignment with a weight equal to the minimum of W1=W(A(G), C(G)) and W2=W(C(G), B(G)). Since W1=77 and W2=100, the resulting weight is set to 77. In the extended library, this new value is added to the previous one to give a total weight of 165 (i.e. 77+88) for the pair A(G), B(G).</i>

[Pic]

was mir doch sehr genau nach der extension folie aus der vorlesung ausschaut..

![t-coffee](https://user-images.githubusercontent.com/22291305/33027849-8b01aa66-ce14-11e7-80ac-a19795a424c6.jpg)

oder wo liegt das problem? bin verwirrt ob der verwirrung... 😄

**Comment by AlexanderMattheis** [comment]
Hi, Martin.
Danke für deine Antworten.
Ich habe gar nicht die Folien gemeint. 
Ich würde behaupten, dass die, die du zeigst vollkommen richtig sind.
Ich hatte irgendwie die alten Folien noch und da war noch ein Fehler drin,
wusste aber nicht, dass ihr den Fehler rausgemacht habt.

**wenn ich k=1 setze, bekomme ich damit wieder den im paper beschriebenen ansatz.. oder?**
Ja, natürlich. Wir reden vom selben.

**<i>Ja, in den Vorlesungs-Folien ist es anders, aber im Paper steht von dem was auf den Folien bei der Extension zu sehen ist glaube ich nichts. Vorallem werden zweimal dieselben miteinander aligniert.</i>**
Ich hatte es leider auf die alten Folien bezogen und da war ein Fehler drin, wusste nicht, dass die alt sind.

**Also, ich glaube, dass es keine Stellen mit 0 geben kann im Original-Algorithmus,
denn die sind erst gar nicht definiert. Im Paper heißt es, dass nur für alignierte Stellen ein Gewicht existiert
und alle alignierten Stellen die Sequenz-Identität als Gewicht erhalten.**
Das ist vielleicht etwas falsch ausgederückt. 
Es heißt, dass nicht-definierte Stellen mit 0 interpretiert werden.
Das heißt, wenn man z.B. nur die global library verwendet, dann gibt es 
"library cells, für die, die primary library = 0 ist", aber es gibt theoretisch unendlich viele und zwar alle undefinierten Stellen. 
Und wenn ich zusätzlich die lokale Library verwende, dann kann es sein, dass eine Stelle, die vorher 0 war,
plötzlich != 0. Aber das hat nichts mit der Extension zu tun, sondern mit der Signal-Addition.
Diese Stellen könnte natürlich irgendwie ermitteln... Am Besten besprechen wir das morgen an meiner Unit-Test PDF. Ich weiß nämlich nicht, wo ich da noch "library cells, für die, die primary library = 0 ist" einbaueb soll.

**Comment by AlexanderMattheis** [comment]
Hi, ihr habt in den alten Folien des untere noch zum Extension-Schritt gezählt, aber das heißt im Paper Signal-Addition... Daher glaube ich resultiert unsere Uneinigkeit... Du willst, dass ich die Stellen, die vor der Signal-Addition 0 sind auch anzeige? War das so gemeint?
![grafik](https://user-images.githubusercontent.com/29164150/33062485-be042bc4-ce9f-11e7-966b-f6b04940e6dd.png)

**Comment by martin-raden** [comment]
nö, reicht die finale primary lib anzuzeigen. die verwendeten alignments listet du ja, sodass man das nachvollziehen kann wenn man will. *daumenhoch*

**Comment by martin-raden** [comment]
bzgl **primlib=0 cells**: da gehts mir wirklich nur um die fälle, bei denen kein direkter match in den alignments vorliegt (primlib nach signal-addition) aber über zwei align-steps mit dritter sequenz dann doch min ein indirekter match in der extlib autaucht. können wir aber morgen nochmal durchgehen..

**Comment by AlexanderMattheis** [comment]
Fertig mit T-Coffee und alles mit Unit-Tests überprüft (17 PDF-Seiten und das nur für die Hauptroutine von T-Coffee).
Hirschberg wird auch bereits etwas angezeigt, aber ich baue den Output noch etwas aus.

**Comment by martin-raden** [comment]
Super, schau ich mir baldigst an. Wird aber nichts vor Montag...

**Comment by martin-raden** [comment]
`Loc(x)` ist doch eigentlich `1..|x|` oder?

**Comment by martin-raden** [comment]
über die texte geh ich dann nochmal drüber. Danke dir!

**Comment by AlexanderMattheis** [comment]
`Loc(x)` ist doch eigentlich `1..|x|` oder?
Jup! Coole Idee, dann braucht man nicht, noch eine Funktion `Loc` einzuführen...

**Comment by martin-raden** [comment]
'daumenhoch' denke das passt!

danke dir!
