### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by AlexanderMattheis** [PerfectionMaschine/RNA-Playground#15]
Hier schreibe ich nicht abgemachte (notwendige) Änderungen hinein.

## 8.11.2017 bis 14.11.2017: T-Coffee
1. Ich habe gemerkt, dass die **Matrizen** alle **spiegelverkehrt** waren bzgl. der Diagonalen.
Also Sequenz a und Sequenz b vertauscht gewesen sind in allen Algorithmen (in den Tabellen).
Das habe ich korrigiert, weil sonst die Argumente in den Formeln vertauscht wären.
_(hatte ewig gedauert, dass zu fixen)_
2. **Alignment=Top** in allen Tabellen-Einträgen gesetzt.  Dadurch sind nun alle Einträge auf selber Höhe.
3. E-Mail zu **"Once a gap, always a gap"**
4. **Performance von T-Coffee maximiert.** 
Die Joining-Prozedur funktioniert ja etwas anders als in Feng-Doolittle.
Man muss für eine bestimmte Gruppe 
den TracebackPath für das Alignment nur einmal ausrechnen
und das nutze ich nun aus -> keine Neuberechnung der Matrix
(ist notwendig, weil der Algorithmus anders als es im Paper heißt
nicht sehr schnell ist (wenn man noch lokale Alignments etc. ausnutzt) -> habe mich erkundigt)
![1](https://user-images.githubusercontent.com/29164150/32692604-59b97baa-c71b-11e7-9548-c110406f061b.PNG)
Im Bild sieht man, dass derselbe Traceback-Path von den zwei Sequenzen **a** und **b** verwendet wird, weil
anders ausgerichtet wird (Durchschnitt von allen Gruppen-Elementen an bestimmter Position, mehr in Unit-Test PDF)
5. **Bug in Feng-Doolittle und zerstörten Code korrigiert.** 
_(hatte ewig gedauert, dass zu fixen)_
6. Zusätzlicher Unit-Test zu Feng-Doolittle.
7. **Sortier-Funktion** für Zahlen-Tupel (i,j) in Tabellen.
8. **Sortier-Funktion** für Cluster-Tupel (a,b) in Tabellen.
9. **Bugs** mit **Live-Update** gefixt.

**Comment by PerfectionMaschine** [comment]
9. **Bugs** mit **Live-Update** gefixt.
