### ISSUE TITLE
meeting 15.11.2017 + 22.11.2017

### ISSUE THREAD

**Issue by martin-raden** [PerfectionMaschine/RNA-Playground#16]
Hallo Alex,
hier mal die Sachen die wir besprochen haben. Kannst du gern ergänzen.

- [x] number of optimal alignments (global def=1, local def=2) [Siehe anderen Thread]
- [x] auflistung der alignments, die für die libraries verwendet wurden (ende der seite, scrollable)
- [x] garfield example = default für FD (mit parametern, sodass beispiel aus tcoffee paper rauskommt 
**from Alex:** ich kann den Baum von denen nicht erzeugen, da meiner deterministisch erzeugt wird ohne PAM-Matrix und deren nicht-deterministisch mit PAM-Matrix (vermutlich))
- [x] FD parameter von oben auch default für tcoffee
- [x] auch library cells auflisten für die primary library =0 ist **[Siehe anderen Thread]**

dann noch eine spontane idee

- [x] tooltip für alle sequenz input fields bzgl. des erlaubten alphabets `Allowed are A-Z and '-'.`

und bzgl Hirschberg

- [x] berechne NW für (a) normale sequenzen und (b) rückwärtssequenzen
- [x] zeige Hirschberg traceback steps an
  - für jede im Hirschberg berechnete finale (sub)zeile die entspechenden daten aus (a) und (b) holen
  - optimale spaltenkombination hervorheben, welche die submatrizen für die nächste iteration definiert
- [x] Ausbauen den Hirschberg Outputs für besseres Verständnis

können wir auch nochmal drüber sprechen, kein problem.

**Comment by AlexanderMattheis** [comment]
Danke für's Issue Opening.^^ Müsste mir sonst viel merken...
**... auch library cells auflisten für die primary library = 0 ist**
Ok, da habe ich bei mir mit deiner Hilfe einen Bug gefunden. 
Bei mir hat es bei dir im Büro, dann klick gemacht. 
Ich hatte völlig vergessen, dass soetwas möglich ist, dass primary library = 0 und extended library ungleich 0 sein kann... Oje, Unit-Test nochmal rechnen...

**Comment by AlexanderMattheis** [comment]
Ich nehme meinen letzten Post zurück. 
Ich habe dir eine Mail geschickt. 
Also, ich glaube, dass es keine Stellen mit 0 geben kann im Original-Algorithmus,
denn die sind erst gar nicht definiert. Im Paper heißt es, dass nur für alignierte Stellen ein Gewicht existiert
und alle alignierten Stellen die Sequenz-Identität als Gewicht erhalten.
Ja, in den Vorlesungs-Folien ist es anders, aber im Paper steht von dem was auf den Folien bei der Extension zu sehen ist glaube ich nichts. Vorallem werden zweimal dieselben miteinander aligniert.

**Comment by AlexanderMattheis** [comment]
Ich glaube, dass das Traceback komplexer ist, als einfach nur Divide & Conquer in Hirschberg.
Habe dir nach meiner Recherche eine PDF geschickt von einem Professor und einem Doktoranden
und auf Seite 9 sieht das Traceback-Verfahren irgendwie anders aus (Intervalle).
Naja, ich habe es mal implementiert wie in der Vorlesung bzw. leicht modifizieren müssen,
damit es konvergiert, aber die Trace-Zellen stimmen nicht immer mit den echten Tracezellen
aus Needleman-Wunsch überein.
Vorallem wie geht man bei mehreren Minima um (falsches Minimum ausgewählt und Fehler wird propagiert) und wie bei den Terminal-Fällen und wie bei horizontalen Lücken? (habe das ganze Wochenende ausprobiert)
Bei Terminalfällen |a| <= 1 und b >= 1 geht das mit dem Minima suchen meistens schief,
weil dann alle Summanden im resultierenden Array denselben Wert haben:
also, Minimum wird ausgewählt, es ist aber keine Traceback-Zelle.

Vielleicht habe ich aber auch nur eine falsche Vorstellung vom Algorithmus...

**Comment by martin-raden** [comment]
**bzgl hirschberg** siehe email, ich glaube du verwendest die falschen zellen aus der "pseudo-rückwärtsrekursions-matrix". grundlegend sollte in jeder (korrekten) vor-rückwärts-zeilenkombination das optimale alignmentergebnis als minimum erscheinen und den trace liefern..
![hirschberg-trace](https://user-images.githubusercontent.com/22291305/33026681-4211af98-ce11-11e7-87f5-0a58ae6d768b.jpg)

für jedes identifizierte (i,j) rekurriert man dann auf die submatrizen (<i,<=j) sowie(>i,>=j)

**Comment by AlexanderMattheis** [comment]
Dankeschön...
Den Fehler mit der falschen Tabelle hatte ich bereits im Hinterkopf, bevor du mir geschrieben hast. 
Hatte wirklich vergessen noch mal zu drehen quasi. Wusste aber, dass das noch nötig ist.
Leider geht der Algorithmus trotzdem schief - kann ich morgen am Minimalbeispiel zeigen,
woran es liegt. 
Das Problem ist, wenn ich die enstehenden zwei Matrizen einfach ausschneiden würde 
und mit den Werten rechnen würde, dann würde ja alles wunderbar klappen... 
und dasselbe Traceback entstehen.
Aber, ich muss ja die Matrix-Werte für die enstehenden Matrizen neurechnen 
(Ja nicht immer! Dass ist mir klar.), 
weil der echte Hirschberg die Werte nicht zwischenspeichert
und dabei wird dann eventuell die falsche Zelle ausgewählt, weil es z.B. mehrere Minima gibt. 
Im aktuellen Unit-Test sieht man das auch: (siehe PDF-Anhang)
![grafik](https://user-images.githubusercontent.com/29164150/33059747-f0b54576-ce95-11e7-84d4-1e420fccdffb.png)
**Rot (umrandet):** vom Algorithmus ausgewählter Wert
**kräftig Blau:** die echte Tracebackzelle

**obere Matrix:** Präfix-Matrix (normal gerechnet)
**untere Matrix:** Suffix-Matrix  (quasi von unten rechts nach oben links gerechnet- enspricht der von dir gedrehten Rückwärts-Rekursionsmatrix \- wobei ich die Sequenzen an die richtige Stelle geschoben habe bzgl. j)
(Match: -1, Mismatch: 1, Gap: 2)
**dritte Tabelle:** Addition der lokalen i-ten Zeilen beider Matrizen,
um das Minimum zu finden ... Problem: 2 Minima

[Hirschberg.pdf](https://github.com/PerfectionMaschine/RNA-Playground/files/1490397/Hirschberg.pdf)

**Hinweis:** Dieses Problem besteht nicht nur in Terminal-Fällen!
Wie gesagt, am Besten besprechen wir das Beispiel morgen,
weil über Mail reden wir immer umeinander rundherum habe ich das Gefühl.
Komme vermutlich heute sowieso nicht mehr zum Lesen...

**Comment by martin-raden** [comment]
ok. denke es gibt ein grundlegendes problem was hirschberg leistet und was nicht. 

sprich damit findet man *nur aligned positions* also die match/mismatch cases und die gaps fallen dann implizit raus..

hab hier mal ein komplettes beispiel durchgerechnet.

![hirsch](https://user-images.githubusercontent.com/22291305/33066142-ce841c60-ceaa-11e7-9952-0c10669e92da.png)

was dabei auffällt, mein statement von oben stimmt nicht ganz, denn man rekurriert immer *exklusive* der identifizierten zeile/spalte.
die idee: das entspricht einer trace transition von einem match bereich über die match-zelle in einen match bereich.
daraus resultieren auch die terminalfälle: wann immer ein bereich *keinen* match mehr enthalten kann, wid abgebrochen, dh `i,j <= 0` oder `i,j > n,m`

fragen? 😄

**Comment by AlexanderMattheis** [comment]
Hi Martin, erstmal danke für all die Hilfe.
Ich komme erst jetzt dazu das durchzulesen. 
Nein, als wir das besprochen haben, war ich anscheinend nicht da oder es wurde nicht gesagt.
Ich höre das zum ersten Mal...
Ich lese mich jetzt mal in den Algorithmus ein und versuche mir den logisch herzuleiten (wenn ich Zeit finde),
um dein Beispiel zu verstehen. Wir haben in der Übung damals nur die erste Zelle ausgerechnet und fertig. Das hat damals bei mir gestimmt und ich war zufrieden...
Daher wusste ich das mit der Rückwärts-Rekursions-Matrix....

Gruß, Alex

**Comment by AlexanderMattheis** [comment]
Hi Martin,
Also algorithmisch ist Hirschberg soweit fertig und getestet (ein neuer Unit-Test und andere aus NW). 
Visuell muss ich "nur" noch die Zwei-Reihen-Tabellen einbinden (mit Toggle-Button wieder). 
Ich rechne auch ein Alignment aus, um gegen NW zu testen. 
Das Traceback wird aus der visualisierten Minima-Map rekonstruiert und auch visuell dargestellt, 
da es iwie auch zum Algorithmus gehört.
Habe, denke ich verstanden wie und wieso man so aufteilen muss, wie ich nun aufteile 
und was sich der Hirschberg dabei vermutlich gedacht hat.
Zu mindest liefere ich eine Erklärung wieso es funktioniert.
Das aus der Vorlesung, so hatte ich es am Mittwoch bereits, hat ja nicht funktioniert.
Also, eventuell sollte man die Vorlesungs-Folien anpassen.

Viele Grüße,
Alex

**Comment by martin-raden** [comment]
Hi Alex,
danke fürs Update, werde versuchen heute nachmittag draufzuschauen. Bin gerade noch mit Vorlesungsvorbereitung ausgelastet.. :/
Liebe Grüsse,
der Martin

**Comment by AlexanderMattheis** [comment]
Fertig mit Hirschberg. Hatte ziemlich gedauert den vollen Output auszugeben.
Habe die Rendering-Zeit mit Knockout verfügbaren Mitteln (kurz: Deferred Rendering)
optimieren müssen, damit es flüssig läuft, da ich wirklich alle Zwei-Reihen Suffix- und Präfix-Alignments ausgebe. Um die Leute nicht zu verwirren, habe ich die Notation aus der Vorlesung übernommen.
Danke für alle Hilfe. Mein Problem war, dass ich gleich ins Paper hätte schauen müssen,
denn mit Vorlesungsfolien und falschen Internet-Erklärungen hatte es nicht geklappt, aber naja habe ziemlich viel gelernt mit dem Algorithmus.
