### ISSUE TITLE
29.11.2017

### ISSUE THREAD

**Issue by martin-raden** [PerfectionMaschine/RNA-Playground#17]
- [x] check comments in 517b235c98d097f560b9e5b5ab6c7e769023cfd2

T-coffee
- [x] check comments in ccf2dfa6b3f23d25210386757a3525b43a29d6ca

Hirschberg
- [x] rekursionen für D und D' anzeigen + formel für s hinter parameter 
**[hab die Rekursionen dynamisch gemacht, da das nicht viel Aufwand war und es dann konsistent mit den anderen Verfahren ist]**
- [x] floor(n) -> floor(n/2)
- [x] ggf. `<br>` durch `<br />` ersetzen um xml warning zu vermeiden
- [x] kommentar 2 bzgl. D' spalten/zeilenlabel (siehe unten)

`mail an Martin` :)

Tree-generation
- [x] input = semikolon-getrenntes inputfeld = textarea 
- [x] check input ob sinnvoll (ignore whitespace) (gleiche spaltenzahl in jeder nichtleeren zeile); ansonsten fehler in "error span" unter input; erst losrechnen wenn sinnvoll.. 
- [x] auswahl an distanzformeln (UPGMA, WPGMA) und formel entsprechend anzeigen
- [x] output wie in FD (baum visuell/newick und zwischenmatrizen)

neighbor-joining 
- [x] in tree-generation integrieren

benennung: bitte folgendes mit bindestrichtrennung umbenennen:
- [x] GotohLocal => Gotoh-Local
- [x] AgglomerativeClustering => Agglomerative-Clustering

**Comment by martin-raden** [comment]
Moin Alex,
bzgl. Hirschberg und D' matrix: kannst du bitte prüfen wieviel arbeit es macht Folgendes umzusetzen:
- *keine* sequenzlabel in der tabelle (vielleicht durch ersetzen/überschreiben der sequenz mit leerstring der gleichen länge?)
- nur zeilen/spaltennummern

damit würde man das interpretationsproblem loswerden...
Danke,
der Martin

**Comment by AlexanderMattheis** [comment]
**"
keine sequenzlabel in der tabelle (vielleicht durch ersetzen/überschreiben der sequenz mit leerstring der gleichen länge?)
nur zeilen/spaltennummern
"**
Jo, könnte ich machen.

**bsp AACG | AATCG trace buggy..** Tritt bei mir nicht auf komischerweise - ich probiere es noch an einem anderen Computer und Browser. **Vielleicht liegt bei dir im Browser-Cache noch eine alte Version der Dateien?**
Kriege das auch mit anderen Browsern nicht hin...

Update: Habe es jetzt auch an zwei anderen Computern getestet (Windows 10 Firefox - kein Problem
und unter Windows 7 - alte Firefox-Version, auch kein Problem...)

![1](https://user-images.githubusercontent.com/29164150/33373210-1f18e262-d501-11e7-9ab2-b3ffbb93649e.PNG)

**Comment by martin-raden** [comment]
mhh... nun läufts bei mir auch.. hatte sich wahrscheinlich wirklich der browser verschluckt. hab den punkt aus der todoliste genommen.

**Comment by AlexanderMattheis** [comment]
Ok, danke. Hatte inzwischen auch unter Linux getestet... 
Ich werde in der letzen Woche auch noch auf Tablets etc. mal schauen, wie es läuft,
um Random auftretende Fehler auszuschließen...

Gruß, Alex

**Comment by martin-raden** [comment]
habe deine letzten commits durchgeschaut und ein paar comments hinterlassen (siehe liste und links oben). bitte auch durchgehen! danke

**Comment by AlexanderMattheis** [comment]
Alles zurückgeändert...

**du musst über alle input alignments summieren, sonst stimmt deine formel nicht! daher die änderung oben! bitte zurückändern!**
Ich hatte total vergessen, dass wir ja jetzt Multiple Optimal Alignments verwenden, ... ich glaube, ich war  gestern abend zu müde.. Sorry...

**diese änderung war absicht, damit das "FE" vom cofFEe erklärbar wird...**
Ah, ok, wie gesagt, ich sollte abends nicht mehr draufschauen...

**warum genau hast du hier x und y vertauscht?**
Das ist eine gute Frage... :) Ich tausche es zurück.

Ok, bin dann weg.

**Comment by AlexanderMattheis** [comment]
Hi Martin,
Ich bin soweit mit den ersten 4 Punkten durch + den Kommentaren. Habe auch noch beim T-Coffee
bei dem Interface was verändert, damit es konsistent ist.
Konnte leider nicht sofort heute anfangen und war noch zwischendurch immer wieder weg, 
daher erst jetzt das Ganze vollendet und wegen den missglückten Veränderungen in der Description, sorry. Ich dachte, dass ich dir etwas Arbeit abnehme, aber naja ... nächstes mal frage ich besser.

**Comment by martin-raden** [comment]
@PerfectionMaschine hab den Hirschbergtext/-rekursionen/-tablelayout überarbeitet..

solltest daher ein "pull" machen, bevor du weitercodest.

Grüsse,
der Martin

**Comment by martin-raden** [comment]
@PerfectionMaschine hab gerade die todo-list mit sachen aktualisiert, die mir noch über den weg gelaufen sind. eilt alles nicht, kann man auch in die nächste woche verschieben. wollt sie nur nicht vergessen. 😄

**Comment by AlexanderMattheis** [comment]
Hoffe damit nun fertig zu sein.
