### ISSUE TITLE
normalized local alignment

### ISSUE THREAD

**Issue by martin-raden** [PerfectionMaschine/RNA-Playground#2]
length-normalized local alignments berechnet man iterativ. dazu:

gegeben: S1, S2, scoring function s(), length factor L (range 0..1000)

1. berechne Smith-Waterman matrix für S1,S2 basierend auf s()
2. finde besten score d1 und laenge des entsprechenden alignments l1 via traceback von d1
3. berechne scalierungsfaktor `lambda1 = d1/(l1+L)`
4. erzeuge neue scoring function s' mit s'(match/mismatch) = s() + 2*lambda1 und s'(gap) = s() + lambda1 (siehe vorlesungsfolie)
5. wiederhole 1-4 mit neuem scoring s'() bis lambda factor konvergiert oder 5mal iteriert
6. finde und liefere alle optimalen lokalen alignments für finales lambda

sprich dafür brauchst du eine lokale SW instanz mit entsprechend angepassten scoringparametern und eine entsprechende iteration.

**Comment by martin-raden** [comment]
- runde zellen auf eine kommastelle
- add `lambda` parameter (default = 0) zum SW-scoring
- immer einzelne zwischentable D^i und entsprechende  d^i, l^i sowie lambda^i anzeigen (drüber "Iteration i" header und höchste iteration topmost; ggf. parameter in den header)

**Comment by martin-raden** [comment]
nenn mal die files `Arslan-Egecioglu-Pevzner.*` etc. da von diesen Autoren [hier 2001](https://doi.org/10.1093/bioinformatics/17.4.327) eingeführt

**Comment by AlexanderMattheis** [comment]
DONE! Habe mich diesmal deinem Schreibstil angepasst bei der Beschreibung.
Das Seite aufzubauen, hat auf Grund von Problemen mit Knockout/MathJax 3.5 Tage gedauert...
Habe zuerst doch versucht das Interface komplett dynamisch aufzubauen (1.5 Tage,
da ich das später sowieso beim Feng-Doolittle vermutlich benötigen werden* oder ich werde dort auch nach bestimmter Zahl von Schritten abbrechen die Sachen anzuzeigen...),
aber LaTeX-Formel im Knockout-Loop ging schief, ObservableArrays etc...

Algorithmus + Unit-Test schreiben + Bugs entfernen etc. (der Unit-Test aus der Vorlesung war fehlerhaft...)
nochmal 1.5 Tage (wobei Bugs die Bugs beim Interface lagen)

\* ich muss mir davor ein Minimalbeispiel schreiben, um zu sehen, ob das mit MathJax gut geht.
Bisher sah es so aus, dass beim Neuladen der Seite MathJax einfach den Loop nicht richtig ausgeführt hat und die Formel mehrfach an die selbe Stelle geschrieben hat...
bei statischen Sachen besteht das Problem aber nicht,
aber vielleicht kriegt man das dynamisch (HTML-Code mit KO generieren) doch irgendwie geregelt...
Ich weiß eventuell nun, warum das mit den ObservableArray schief gelaufen ist bei meinem ersten Versuch: Matrizen müssen alle gemeinsam gespeichert werden und Alignments getrennt davon alle gemeinsam - man darf nicht eine große Menge mit Alignments und Matrizen erzeugen, über die man drüberitteriert (da gibt es Probleme) ...

**Comment by martin-raden** [comment]
wunderbar, schau ich mir baldigst an! 😄

**Comment by martin-raden** [comment]
ok, schöne sache. habe die texte/labels überarbeitet und hier noch ein paar kleine todos:

- [x] die download links funktionieren nur für die angezeigten tables und sollten entsprechend dynamisch angezeigt werden
- [x] bei mir wird kein traceback angezeigt.. wär schön wenn der ausgewählte auch angezeigt wird
- [ ] es reicht EIN alignment pro table auszurechnen und anzuzeigen (dann ist man auch nicht versucht ein anderes auszuwählen)
- [x] die interaktive cell-trace funktion on selection ist scheinbar nicht aktiv. absicht?

**Comment by AlexanderMattheis** [comment]
Ich habe den Visualizer, um die Cell-Trace-Funktion für Arrays von Tabellen erweitert.
Ich wünschte, ich hätte alles von Anfang an komplett generisch mit Arrays gemacht,
aber ich hatte mit dem Algorithmus am Anfang nicht gerechnet.
Traceback wird für das "von Anfang an" markierte Ergebnis angezeigt.
Bei den Downloads habe ich auf 4 Stellen erweitert, also falls jemand die angezeigte Tabelle von der Genauigkeit her nicht ausreicht, dann kann er sich immer noch die Tabelle mit höherer Genauigkeit runterladen. :)
Das mit den Alignments hatten wir ja besprochen... Ich könnte natürlich nur eins anzeigen, aber dann lohnt sich die Results-Table nicht wirklich und so... ich müsste unterscheiden...
bis nächste Woche ... muss noch das mit den Divs für den Algorithmus-Input machen und dann kann ich endlich an Feng-Doolittle ran (da mache ich alles generisch... :))

**Comment by martin-raden** [comment]
klingt schon mal super, schau ich mir am montag an!

bzgl. alignmentliste: was halt auch ein bissl komisch ist, wenn man 5 alignments anzeigt und (weil richtig) nur eins verwendet. wenn das so ist, solltest du einen entsprechenden hinweis drunterpacken, dass die alternativalignments nicht verwendet werden und nur der vollständigkeit halber gelistet werden.

schönes wochenende!

**Comment by AlexanderMattheis** [comment]
Ebenfalls schönes Wochenende.
Mache ich bzw. eigentlich steht da schon eine andere Überschrift. :)

[Erledigt! :)]

Hinweis: sprites.png wurde verändert und umbenannt zu inner_sprites.png (wegen Server)...

**Comment by martin-raden** [comment]
sieht gut aus, danke!
