### ISSUE TITLE
newline character

### ISSUE THREAD

**Issue by martin-raden** [PerfectionMaschine/RNA-Playground#5]
sollte das newline encoding nicht nur `\n` sein anstatt per default die gruslige windows variante `\r\n` ?

https://github.com/PerfectionMaschine/RNA-Playground/blob/7918de8b4e3da7b88a099f4a2e03d31fc70fb7f0/js/defaults.js#L309

oder könntest das user/browser specific machen?

**Comment by AlexanderMattheis** [comment]
Geändert. Browser/User Specific ginge vielleicht auch...
