### ISSUE TITLE
external js lib

### ISSUE THREAD

**Issue by martin-raden** [PerfectionMaschine/RNA-Playground#7]
kannst du diese lib bitte noch lokal ablegen

https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML

damit wir keine extenen dependencies haben?

**Comment by AlexanderMattheis** [comment]
Nein, das geht glaube ich ausnahmsweise nicht (kann aber noch schauen mal). 
Man muss das soweit ich weiß so machen:
http://docs.mathjax.org/en/latest/start.html
Wenn ich mich richtig errinnere ist das serverseitiges Javascript? und kein client-seitiges Javascript:
http://docs.mathjax.org/en/latest/installation.html
Ist aber in RNA-Playground auch nicht anders (genauso gemacht), 
wobei der Link in RNA-Playground, wie mir gerade auffält ausgetauscht werden muss (Warnung in Firefox beim Drücken von F12).

**Comment by martin-raden** [comment]
habs schon fast vermutet.
kannst die issue schliessen, wenn du den link getauschst hast..
danke!
