### ISSUE TITLE
zuviel voodoo in alignment.html

### ISSUE THREAD

**Issue by martin-raden** [PerfectionMaschine/RNA-Playground#8]
Moin,
ich versuch gerade das ganze zu integrieren und scheitere an deinem loader voodoo mit dem du das alignment.html füllst.

ich brauche eine simple strategie/script/whatever, welches mir für ein gegebenen algonamen zB "Gotoh" die entsprechende seite lädt. nur die algo-page einzubetten reicht ja scheinbar nicht, da die entsprechenden datenstrukturen nicht initialisiert werden.

derzeit ist der loader absolut hart auf das dropdown setup im alignment.html abgestimmt, was so nicht gut ist! bzw. ok, aber dann brauch ich ein scriptset, was ich anstelle des loaders nutzen kann, um einen einzelnen algo auch in einer anderen seite zu laden.

Danke

**Comment by martin-raden** [comment]
Waer gut wenn entweder das einbinden der algoseite via jquery.load (siehe index.htm) direkt alles veranlasst oder wenn du eine js routine schreibst, die eine geladene algoseite 'aktiviert'

**Comment by AlexanderMattheis** [comment]
Hi Martin, bin gerade etwas überfragt. Mehr oder weniger macht die loader.js
"
ich brauche eine simple strategie/script/whatever, welches mir für ein gegebenen algonamen zB "Gotoh" die entsprechende seite lädt. nur die algo-page einzubetten reicht ja scheinbar nicht, da die entsprechenden datenstrukturen nicht initialisiert werden.
"
genau das in der updateDocumentView-Funktion.

Ich hatte zu Beginn immer die HTML-Seite genau wie das dazu verantworliche Javascript genannt.
Bei der Migration zu RNA-Playground musste ich was umbennen, daher ist das jetzt verwirrend.

Das eigentliche Laden geschieht in der Funktion updateDocumentView in der loader.js.
Ich musste, dass aber deshalb so machen, damit die Deprecation-Warnung

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/

 in Firefox vermieden werden:
https://stackoverflow.com/questions/24639335/javascript-console-log-causes-error-synchronous-xmlhttprequest-on-the-main-thr

Die Meldung kommt bei RNA-Playground, weil die Scripte zum initialisieren mancher Strukturen direkt in der HTML
von der Algorithmus-Page am Ende der Seite geladen werden: (das ist aber laut stackoverflow nicht gut)
```
<div> 
 SOME CONTENT HERE
</div>
<script src="/scripts/script.js"></script>
```

In der updateDocumentView hatte ich es ja so, 
dass die Algorithmus-Page und das zugehörige Script mit dem selben Namen (aber! in Kleinbuchstaben und Unterstrichen) geladen werden. (bei mir ist es immer so, dass Algorithmus-Script und Page quasi gleich heißen)
Der "view" ist ja bloß, dass Div in das geladen werden soll 
und "algorithm" ist der Name, der im "algorithm_menu" steht. 
Dieser Name wird abgeändert, damit die entsprechende Seite
geladen wird:

`<div id="algorithm_menu">
                <ul>
                    <li><a href="#">Arslan-Eğecioğlu-Pevzner</a></li>
                    <li><a href="#">Gotoh</a></li>
                    <li><a href="#">Needleman-Wunsch</a></li>
                    <li><a href="#">Smith-Waterman</a></li>
                    <li><a href="#">Waterman-Smith-Beyer</a></li>
                </ul>
            </div>`
```
function updateDocumentView(algorithm, view) {
        var htmlName = ...
        var javascriptName = ...

        view.load(PATHS.MAIN.PAGES + htmlName + FILE_EXTENSIONS.HYPERTEXT_MARKUP_LANGUAGE, function () {
            $.getScript(PATHS.MAIN.SCRIPTS + javascriptName + FILE_EXTENSIONS.JAVASCRIPT);
        });
    }
```
Außerdem muss in den html-Tag bei dir auf der Page
`   <div id="overlay"></div>`
platziert werden und dann sollte alles klappen, wenn
vor dem Laden 
`$("#overlay").empty()`
aufgerufen wird.

Hoffe das hilft.
Wir könnten am Mittwoch noch gemeinsam schauen.
Ich weiß, aber gerade nicht, wie ich da genau für ein Script dir schreiben könnte.

Viele Grüße,
Alex

**Comment by martin-raden** [comment]
ich denke, dass folgendes
```html
$(document).ready(function () {
    loader.startLoader();
});
```
beim laden crashed, weil es auf das dropdown zugreift. damit ist dann aber der rest vom file auch nicht definiert, sodass das angehangene testAlignment.html auch nicht läuft mit der meldung
```
TypeError: loader.updateDocumentView is not a function
```
oder wo genau mach ich was falsch?


[testAlignment.html.txt](https://github.com/PerfectionMaschine/RNA-Playground/files/1381709/testAlignment.html.txt)

**Comment by AlexanderMattheis** [comment]
Jetzt verstehe ich. 
Bei mir gibt es private- und public-Methoden.
Und updateDocumentView ist bloß private und daher findet er updateDocumentView nicht.

updateDocumentView muss bloß im Namespace der loader.js deklariert werden,
dann klappt es:

```
function () {  // namespace
    // public methods
    namespace("loader", startLoader, updateDocumentView);
```

Ich habe hier die Files, die du ersetzen müsstest, damit alles ohne Fehler klappt mal vorbereitet.
Bei mir klappt es dann, aber das 
http://rna.informatik.uni-freiburg.de/resources/corporate-design.css
zerschießt den Flow meiner Divs aus irgendeinem Grund...
Alle Divs sind an der falschen Stelle...

[inner_style.css.txt](https://github.com/PerfectionMaschine/RNA-Playground/files/1381970/inner_style.css.txt)
[testAlignment.html.txt](https://github.com/PerfectionMaschine/RNA-Playground/files/1381971/testAlignment.html.txt)
[loader.js.txt](https://github.com/PerfectionMaschine/RNA-Playground/files/1381972/loader.js.txt)
[defaults.js.txt](https://github.com/PerfectionMaschine/RNA-Playground/files/1381973/defaults.js.txt)

Ich muss leider jetzt weg...

**Comment by martin-raden** [comment]
danke dir, werds gleich mal testen!

**Comment by martin-raden** [comment]
super, funktioniert! vielen dank!

das css-problem lässt sich lösen, in dem die standard margins der divs deaktiviert werden mit 
```html
<style type="text/css">
	#algopage * div,table {
		margin: 0;
	}
</style>
```
