### ISSUE TITLE
WSB traceback bug

### ISSUE THREAD

**Issue by martin-raden** [PerfectionMaschine/RNA-Playground#9]
wenn ich WSB mit quadratischer gap function und einem (unrealistischen) beta=+1 wähle, dann springt der traceback *direkt* von (n,n) nach (1,1) und nicht erst waagerecht und dann senkrecht, wie erwartet. dementsprechend ist auch das alignment falsch und zeigt nur eine sequenz:
```
CCGA
    
____
```

**Comment by AlexanderMattheis** [comment]
Danke, ich schau mal was da nicht klappt.

**Comment by AlexanderMattheis** [comment]
Ich hatte die Formel nicht ganz richtig implemntiert im Traceback...
Statt "<=" hatte ich ein "<" stehen.
Korrigiert...
